const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Clean benefits on re-seed
  await prisma.benefit.deleteMany({});

  // Create Categories
  const bancosCategory = await prisma.providerCategory.upsert({
    where: { slug: 'banco' },
    update: {},
    create: { name: 'Banco', slug: 'banco', icon: '🏦' },
  });

  const telefoniaCategory = await prisma.providerCategory.upsert({
    where: { slug: 'telefonia' },
    update: {},
    create: { name: 'Telefonía', slug: 'telefonia', icon: '📱' },
  });

  const retailCategory = await prisma.providerCategory.upsert({
    where: { slug: 'retail' },
    update: {},
    create: { name: 'Retail', slug: 'retail', icon: '🛍️' },
  });

  const segurosCategory = await prisma.providerCategory.upsert({
    where: { slug: 'seguros' },
    update: {},
    create: { name: 'Seguros', slug: 'seguros', icon: '🛡️' },
  });

  const entretenimientoCategory = await prisma.providerCategory.upsert({
    where: { slug: 'entretenimiento' },
    update: {},
    create: { name: 'Entretenimiento', slug: 'entretenimiento', icon: '🎬' },
  });

  // Create Providers
  const providers = [
    // Bancos
    {
      name: 'BCI',
      slug: 'bci',
      description: 'Banco de Crédito e Inversiones - tarjetas y beneficios exclusivos',
      logoUrl: 'https://www.google.com/s2/favicons?domain=bci.cl&sz=128',
      categoryId: bancosCategory.id,
    },
    {
      name: 'Santander',
      slug: 'santander',
      description: 'Banco Santander Chile - beneficios para tarjetahabientes',
      logoUrl: 'https://www.google.com/s2/favicons?domain=santander.cl&sz=128',
      categoryId: bancosCategory.id,
    },
    {
      name: 'Banco de Chile',
      slug: 'banco-de-chile',
      description: 'Banco de Chile - Club de Beneficios exclusivos',
      logoUrl: 'https://www.google.com/s2/favicons?domain=bancochile.cl&sz=128',
      categoryId: bancosCategory.id,
    },
    {
      name: 'Itaú',
      slug: 'itau',
      description: 'Banco Itaú Chile - descuentos y promociones',
      logoUrl: 'https://www.google.com/s2/favicons?domain=itau.cl&sz=128',
      categoryId: bancosCategory.id,
    },
    {
      name: 'Scotiabank',
      slug: 'scotiabank',
      description: 'Scotiabank Chile - beneficios para clientes',
      logoUrl: 'https://www.google.com/s2/favicons?domain=scotiabank.cl&sz=128',
      categoryId: bancosCategory.id,
    },
    {
      name: 'Banco Security',
      slug: 'banco-security',
      description: 'Banco Security - beneficios exclusivos para clientes',
      logoUrl: 'https://www.google.com/s2/favicons?domain=security.cl&sz=128',
      categoryId: bancosCategory.id,
    },
    {
      name: 'Banco Falabella',
      slug: 'banco-falabella',
      description: 'Banco Falabella - CMR Visa y beneficios en el ecosistema Falabella',
      logoUrl: 'https://www.google.com/s2/favicons?domain=bancofalabella.cl&sz=128',
      categoryId: bancosCategory.id,
    },
    {
      name: 'BancoEstado',
      slug: 'banco-estado',
      description: 'BancoEstado - beneficios para cuenta RUT y tarjetas',
      logoUrl: 'https://www.google.com/s2/favicons?domain=bancoestado.cl&sz=128',
      categoryId: bancosCategory.id,
    },
    // Telefonía
    {
      name: 'Entel',
      slug: 'entel',
      description: 'Entel - beneficios exclusivos para clientes Entel',
      logoUrl: 'https://www.google.com/s2/favicons?domain=entel.cl&sz=128',
      categoryId: telefoniaCategory.id,
    },
    {
      name: 'Movistar',
      slug: 'movistar',
      description: 'Movistar Chile - descuentos y beneficios para clientes',
      logoUrl: 'https://www.google.com/s2/favicons?domain=movistar.cl&sz=128',
      categoryId: telefoniaCategory.id,
    },
    {
      name: 'Claro',
      slug: 'claro',
      description: 'Claro Chile - Club de Beneficios para clientes',
      logoUrl: 'https://www.google.com/s2/favicons?domain=claro.cl&sz=128',
      categoryId: telefoniaCategory.id,
    },
    {
      name: 'WOM',
      slug: 'wom',
      description: 'WOM Chile - beneficios para clientes WOM',
      logoUrl: 'https://www.google.com/s2/favicons?domain=wom.cl&sz=128',
      categoryId: telefoniaCategory.id,
    },
    // Retail
    {
      name: 'CMR Falabella',
      slug: 'cmr-falabella',
      description: 'Tarjeta CMR Falabella - descuentos en Falabella y partners',
      logoUrl: 'https://www.google.com/s2/favicons?domain=falabella.com&sz=128',
      categoryId: retailCategory.id,
    },
    {
      name: 'Ripley Card',
      slug: 'ripley-card',
      description: 'Tarjeta Ripley - beneficios en tiendas Ripley y partners',
      logoUrl: 'https://www.google.com/s2/favicons?domain=ripley.cl&sz=128',
      categoryId: retailCategory.id,
    },
    {
      name: 'La Polar Card',
      slug: 'la-polar-card',
      description: 'Tarjeta La Polar - descuentos y cuotas sin interés',
      logoUrl: 'https://www.google.com/s2/favicons?domain=lapolar.cl&sz=128',
      categoryId: retailCategory.id,
    },
    // Seguros
    {
      name: 'MetLife',
      slug: 'metlife',
      description: 'MetLife Chile - seguros y beneficios de salud y bienestar',
      logoUrl: 'https://www.google.com/s2/favicons?domain=metlife.cl&sz=128',
      categoryId: segurosCategory.id,
    },
  ];

  const createdProviders = {};
  for (const provider of providers) {
    const created = await prisma.provider.upsert({
      where: { slug: provider.slug },
      update: { logoUrl: provider.logoUrl },
      create: provider,
    });
    createdProviders[provider.slug] = created;
  }

  // Create Benefits
  const benefits = [
    // ─── BCI (8 benefits) ───────────────────────────────────────────
    {
      title: '20% dcto en Café Hauteville',
      description: 'Descuento en todas las sucursales de Café Hauteville pagando con BCI.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['bci'].id,
      terms: 'Válido lunes a viernes. Máximo $3.000 de descuento.',
      validDays: [],
    },
    {
      title: '2x1 en Cines Cinemark',
      description: 'Lleva a un amigo gratis a cualquier función en Cinemark con tarjeta BCI.',
      discount: '2x1',
      type: 'FREEBIE',
      category: 'Cine',
      providerId: createdProviders['bci'].id,
      terms: 'Válido lunes a jueves. Excluye estrenos y funciones 3D premium.',
      validDays: [1, 2, 3, 4],
    },
    {
      title: '15% dcto en Cruz Verde',
      description: 'Descuento en farmacias Cruz Verde con tarjeta BCI.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Salud',
      providerId: createdProviders['bci'].id,
      terms: 'No incluye medicamentos con receta. Válido en todas las sucursales.',
      validDays: [],
    },
    {
      title: '20% dcto en restaurantes partner',
      description: 'Descuento en más de 150 restaurantes asociados a BCI en todo Chile.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Restaurante',
      providerId: createdProviders['bci'].id,
      terms: 'Máximo $15.000 de descuento por transacción.',
      validDays: [],
    },
    {
      title: '15% dcto en Ripley Moda',
      description: 'Descuento en toda la línea de ropa y accesorios de Ripley.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['bci'].id,
      terms: 'Excluye electrodomésticos y tecnología.',
      validDays: [],
    },
    {
      title: '30% dcto en Smartfit',
      description: 'Membresía mensual en Smartfit con 30% de descuento pagando con BCI.',
      discount: '30%',
      type: 'PERCENTAGE',
      category: 'Deporte',
      providerId: createdProviders['bci'].id,
      terms: 'Aplica en planes mensuales. No acumulable con otras ofertas.',
      validDays: [],
    },
    {
      title: '10% dcto en LATAM Airlines',
      description: 'Descuento en pasajes nacionales e internacionales en LATAM.',
      discount: '10%',
      type: 'PERCENTAGE',
      category: 'Viajes',
      providerId: createdProviders['bci'].id,
      terms: 'Válido en compras en latamairlines.com. No aplica en impuestos.',
      validDays: [],
    },
    {
      title: '15% dcto en Teatro Municipal',
      description: 'Descuento en entradas para funciones del Teatro Municipal de Santiago.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Eventos',
      providerId: createdProviders['bci'].id,
      terms: 'Sujeto a disponibilidad. No aplica en estrenos de temporada.',
      validDays: [],
    },

    // ─── Santander (8 benefits) ──────────────────────────────────────
    {
      title: '25% dcto en Uber Eats',
      description: 'Obtén 25% de descuento en tus pedidos de Uber Eats.',
      discount: '25%',
      type: 'PERCENTAGE',
      category: 'Restaurante',
      providerId: createdProviders['santander'].id,
      terms: 'Mínimo $8.000. Máximo 4 usos por mes.',
      validDays: [],
    },
    {
      title: '30% dcto en hoteles Booking',
      description: 'Reserva hoteles con hasta 30% de descuento en booking.com.',
      discount: '30%',
      type: 'PERCENTAGE',
      category: 'Viajes',
      providerId: createdProviders['santander'].id,
      terms: 'Hoteles seleccionados. Reserva con al menos 7 días de anticipación.',
      validDays: [],
    },
    {
      title: '$5.000 dcto en COPEC',
      description: 'Acumula $5.000 de descuento en COPEC al gastar $50.000.',
      discount: '$5.000',
      type: 'AMOUNT',
      category: 'Combustible',
      providerId: createdProviders['santander'].id,
      terms: 'Aplica en estaciones COPEC seleccionadas. Máximo 1 vez por mes.',
      validDays: [],
    },
    {
      title: '20% dcto en Starbucks',
      description: 'Descuento en todas las bebidas y alimentos de Starbucks de lunes a viernes.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['santander'].id,
      terms: 'Válido en tiendas Starbucks participantes. No incluye mercancía.',
      validDays: [1, 2, 3, 4, 5],
    },
    {
      title: '15% dcto en Jumbo',
      description: 'Descuento en compras en supermercados Jumbo los martes y jueves.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Supermercado',
      providerId: createdProviders['santander'].id,
      terms: 'Compra mínima $20.000. Excluye licores y tabaco.',
      validDays: [2, 4],
    },
    {
      title: '20% dcto en H&M',
      description: 'Descuento en toda la tienda H&M pagando con tarjeta Santander.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['santander'].id,
      terms: 'No acumulable con otras promociones. Válido en tiendas físicas.',
      validDays: [],
    },
    {
      title: '2x1 en Cine Hoyts',
      description: 'Compra una entrada y lleva a un acompañante gratis en Hoyts.',
      discount: '2x1',
      type: 'FREEBIE',
      category: 'Cine',
      providerId: createdProviders['santander'].id,
      terms: 'Válido lunes a miércoles. Solo para funciones 2D.',
      validDays: [1, 2, 3],
    },
    {
      title: '20% dcto en conciertos Ticket Plus',
      description: 'Descuento en entradas para conciertos y eventos en Ticket Plus.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Eventos',
      providerId: createdProviders['santander'].id,
      terms: 'Sujeto a disponibilidad de eventos participantes.',
      validDays: [],
    },

    // ─── Banco de Chile (8 benefits) ────────────────────────────────
    {
      title: '10% dcto en LATAM / LAN',
      description: 'Descuento en pasajes nacionales e internacionales.',
      discount: '10%',
      type: 'PERCENTAGE',
      category: 'Viajes',
      providerId: createdProviders['banco-de-chile'].id,
      terms: 'Válido en latamairlines.com. No aplica en impuestos ni tasas.',
      validDays: [],
    },
    {
      title: 'Netflix 3 meses gratis',
      description: 'Accede a 3 meses de Netflix gratis al pagar con Banco de Chile.',
      discount: '3 meses gratis',
      type: 'FREEBIE',
      category: 'Streaming',
      providerId: createdProviders['banco-de-chile'].id,
      terms: 'Solo para nuevos suscriptores. Aplica plan estándar.',
      validDays: [],
    },
    {
      title: '15% dcto en Falabella.com',
      description: 'Ahorra 15% en ropa y accesorios en Falabella.com.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['banco-de-chile'].id,
      terms: 'Compra mínima $30.000. Excluye tecnología y electrodomésticos.',
      validDays: [],
    },
    {
      title: '20% dcto en Juan Valdez Café',
      description: 'Descuento en bebidas y alimentos de Juan Valdez Café.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['banco-de-chile'].id,
      terms: 'Válido en todas las sucursales de Juan Valdez en Chile.',
      validDays: [],
    },
    {
      title: '15% dcto en Paris (ropa)',
      description: 'Descuento en ropa, calzado y accesorios en tiendas Paris.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['banco-de-chile'].id,
      terms: 'No aplica en electrónica ni línea blanca.',
      validDays: [],
    },
    {
      title: '20% dcto en Lider/Walmart',
      description: 'Descuento los miércoles en supermercados Lider y Walmart.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Supermercado',
      providerId: createdProviders['banco-de-chile'].id,
      terms: 'Compra mínima $15.000. Solo los días miércoles.',
      validDays: [3],
    },
    {
      title: '30% dcto en Óptica Lafam',
      description: 'Descuento en lentes, marcos y exámenes visuales en Óptica Lafam.',
      discount: '30%',
      type: 'PERCENTAGE',
      category: 'Salud',
      providerId: createdProviders['banco-de-chile'].id,
      terms: 'Aplica en productos seleccionados.',
      validDays: [],
    },
    {
      title: '20% dcto en The Food Market',
      description: 'Descuento en restaurantes del grupo The Food Market (Puerto Fuy, Osaka, etc.).',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Restaurante',
      providerId: createdProviders['banco-de-chile'].id,
      terms: 'Reserva previa recomendada. No incluye bebidas alcohólicas.',
      validDays: [],
    },

    // ─── Itaú (7 benefits) ───────────────────────────────────────────
    {
      title: '20% dcto en Rappi',
      description: 'Descuento en todos tus pedidos de Rappi con tarjeta Itaú.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Restaurante',
      providerId: createdProviders['itau'].id,
      terms: 'Máximo $3.000 de descuento. Hasta 3 usos por semana.',
      validDays: [],
    },
    {
      title: '$10.000 bono Apple Store',
      description: 'Bono de $10.000 en compras en Apple Store Chile.',
      discount: '$10.000',
      type: 'AMOUNT',
      category: 'Tecnología',
      providerId: createdProviders['itau'].id,
      terms: 'Compra mínima $100.000. Solo en Apple Store física.',
      validDays: [],
    },
    {
      title: '2x1 en Teatro Municipal',
      description: 'Compra una entrada y lleva a un acompañante gratis.',
      discount: '2x1',
      type: 'FREEBIE',
      category: 'Eventos',
      providerId: createdProviders['itau'].id,
      terms: 'Válido para funciones seleccionadas. Compra en taquilla o online.',
      validDays: [],
    },
    {
      title: '20% dcto en The Coffee Shop',
      description: 'Descuento en cafeterías The Coffee Shop con tarjeta Itaú.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['itau'].id,
      terms: 'Válido en bebidas calientes y frías. No incluye alimentos.',
      validDays: [],
    },
    {
      title: '15% dcto en Adidas',
      description: 'Descuento en tiendas Adidas pagando con tarjeta Itaú.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['itau'].id,
      terms: 'Aplica en ropa, calzado y accesorios Adidas.',
      validDays: [],
    },
    {
      title: '25% dcto en Despegar.com',
      description: 'Descuento en paquetes de viaje en Despegar.com.',
      discount: '25%',
      type: 'PERCENTAGE',
      category: 'Viajes',
      providerId: createdProviders['itau'].id,
      terms: 'Aplica en paquetes vuelo + hotel. Monto mínimo $200.000.',
      validDays: [],
    },
    {
      title: '15% dcto en Cinépolis',
      description: 'Descuento en entradas para cualquier función en Cinépolis.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Cine',
      providerId: createdProviders['itau'].id,
      terms: 'Válido de lunes a domingo. Excluye funciones premium.',
      validDays: [],
    },

    // ─── Scotiabank (6 benefits) ─────────────────────────────────────
    {
      title: '25% dcto en Smartfit',
      description: 'Membresía Smart Fit con 25% de descuento.',
      discount: '25%',
      type: 'PERCENTAGE',
      category: 'Deporte',
      providerId: createdProviders['scotiabank'].id,
      terms: 'Aplica en membresías mensuales y anuales.',
      validDays: [],
    },
    {
      title: '15% dcto en viajes internacionales',
      description: 'Descuento en paquetes de viaje con agencias participantes.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Viajes',
      providerId: createdProviders['scotiabank'].id,
      terms: 'Consultar disponibilidad en agencias partner.',
      validDays: [],
    },
    {
      title: '20% dcto en Café Tavelli',
      description: 'Descuento en Café Tavelli, pizzas y pastas artesanales.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['scotiabank'].id,
      terms: 'Válido en consumo en local. No delivery.',
      validDays: [],
    },
    {
      title: '15% dcto en Nike Store',
      description: 'Descuento en ropa y calzado Nike en tiendas oficiales.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['scotiabank'].id,
      terms: 'Aplica en tiendas físicas y nike.com.cl.',
      validDays: [],
    },
    {
      title: '2x1 en CineHoyts Premiere',
      description: 'Entrada 2x1 en Cine Hoyts de martes a jueves.',
      discount: '2x1',
      type: 'FREEBIE',
      category: 'Cine',
      providerId: createdProviders['scotiabank'].id,
      terms: 'Solo funciones 2D. No incluye palomitas ni bebidas.',
      validDays: [2, 3, 4],
    },
    {
      title: '20% dcto en restaurantes Puerto Madero',
      description: 'Descuento viernes y sábados en restaurantes Puerto Madero.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Restaurante',
      providerId: createdProviders['scotiabank'].id,
      terms: 'Reserva requerida. Solo cenas.',
      validDays: [5, 6],
    },

    // ─── Banco Security (6 benefits) ────────────────────────────────
    {
      title: '20% dcto en restaurantes selectos',
      description: 'Descuentos en más de 200 restaurantes a nivel nacional.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Restaurante',
      providerId: createdProviders['banco-security'].id,
      terms: 'Válido en restaurantes adheridos al programa Security.',
      validDays: [],
    },
    {
      title: 'Acceso VIP sala aeropuerto',
      description: 'Acceso gratuito a salas VIP en aeropuertos de Chile.',
      discount: 'Gratis',
      type: 'FREEBIE',
      category: 'Viajes',
      providerId: createdProviders['banco-security'].id,
      terms: 'Tarjetas Black y Platinum. 4 accesos gratuitos por año.',
      validDays: [],
    },
    {
      title: '15% dcto en Café de la Candelaria',
      description: 'Descuento en el histórico Café de la Candelaria en Santiago.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['banco-security'].id,
      terms: 'Válido en consumo de lunes a sábado.',
      validDays: [],
    },
    {
      title: '25% dcto en Teatro Nescafé de las Artes',
      description: 'Descuento en entradas para espectáculos en Teatro Nescafé.',
      discount: '25%',
      type: 'PERCENTAGE',
      category: 'Eventos',
      providerId: createdProviders['banco-security'].id,
      terms: 'Sujeto a disponibilidad de eventos.',
      validDays: [],
    },
    {
      title: '20% dcto en tiendas Zara',
      description: 'Descuento en Zara pagando con tarjeta Security.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['banco-security'].id,
      terms: 'Solo en tiendas físicas Zara Chile.',
      validDays: [],
    },
    {
      title: '15% dcto en Clínica Alemana',
      description: 'Descuento en consultas y procedimientos en Clínica Alemana.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Salud',
      providerId: createdProviders['banco-security'].id,
      terms: 'Aplica en prestaciones ambulatorias seleccionadas.',
      validDays: [],
    },

    // ─── Banco Falabella (7 benefits) ────────────────────────────────
    {
      title: '10% dcto en Falabella todos los días',
      description: 'Descuento permanente en ropa, calzado y accesorios Falabella.',
      discount: '10%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['banco-falabella'].id,
      terms: 'No aplica en tecnología ni electrodomésticos.',
      validDays: [],
    },
    {
      title: '12 cuotas sin interés en Linio',
      description: 'Compra tecnología en Linio.cl en hasta 12 cuotas sin interés.',
      discount: '12 cuotas sin interés',
      type: 'SPECIAL',
      category: 'Tecnología',
      providerId: createdProviders['banco-falabella'].id,
      terms: 'Monto mínimo $20.000. Productos seleccionados.',
      validDays: [],
    },
    {
      title: '20% dcto en Viajes Falabella',
      description: 'Reserva viajes con 20% de descuento en Viajes Falabella.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Viajes',
      providerId: createdProviders['banco-falabella'].id,
      terms: 'Válido en paquetes completos (vuelo + hotel).',
      validDays: [],
    },
    {
      title: '15% dcto martes en Falabella',
      description: 'Cada martes 15% de descuento adicional en toda la tienda.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['banco-falabella'].id,
      terms: 'Aplica sobre precio ya rebajado.',
      validDays: [2],
    },
    {
      title: '20% dcto en Café Haiti',
      description: 'Descuento en el clásico Café Haití de Santiago.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['banco-falabella'].id,
      terms: 'Válido en bebidas y alimentos de lunes a viernes.',
      validDays: [],
    },
    {
      title: 'Puntos CMR dobles en combustible',
      description: 'Doble acumulación de puntos CMR al cargar combustible.',
      discount: '2x puntos',
      type: 'SPECIAL',
      category: 'Combustible',
      providerId: createdProviders['banco-falabella'].id,
      terms: 'Aplica en estaciones de servicio Falabella.',
      validDays: [],
    },
    {
      title: '20% dcto en Sodimac (herramientas)',
      description: 'Descuento en herramientas y equipos en Sodimac.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Tecnología',
      providerId: createdProviders['banco-falabella'].id,
      terms: 'Excluye ofertas especiales y liquidaciones.',
      validDays: [],
    },

    // ─── BancoEstado (6 benefits) ────────────────────────────────────
    {
      title: '10% dcto con Cuenta RUT',
      description: 'Descuento en más de 500 comercios con Cuenta RUT.',
      discount: '10%',
      type: 'PERCENTAGE',
      category: 'Supermercado',
      providerId: createdProviders['banco-estado'].id,
      terms: 'Aplica en comercios adheridos en todo Chile.',
      validDays: [],
    },
    {
      title: 'Seguro de vida gratuito',
      description: 'Seguro de vida básico gratuito para clientes BancoEstado.',
      discount: 'Gratis',
      type: 'FREEBIE',
      category: 'Seguros',
      providerId: createdProviders['banco-estado'].id,
      terms: 'Aplica con cuenta corriente activa. Cobertura UF 50.',
      validDays: [],
    },
    {
      title: '15% dcto en Unimarc',
      description: 'Descuento en supermercados Unimarc los lunes y jueves.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Supermercado',
      providerId: createdProviders['banco-estado'].id,
      terms: 'Compra mínima $10.000.',
      validDays: [1, 4],
    },
    {
      title: '10% dcto en Castaño Café',
      description: 'Descuento en cadena de cafés Castaño pagando con BancoEstado.',
      discount: '10%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['banco-estado'].id,
      terms: 'Válido en bebidas calientes. No incluye alimentos.',
      validDays: [],
    },
    {
      title: '15% dcto en eventos Puntoticket',
      description: 'Descuento en entradas para eventos en Puntoticket.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Eventos',
      providerId: createdProviders['banco-estado'].id,
      terms: 'Sujeto a disponibilidad de eventos participantes.',
      validDays: [],
    },
    {
      title: '20% dcto en Salcobrand',
      description: 'Descuento en productos de salud y belleza en Salcobrand.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Salud',
      providerId: createdProviders['banco-estado'].id,
      terms: 'No incluye medicamentos con receta.',
      validDays: [],
    },

    // ─── Entel (7 benefits) ──────────────────────────────────────────
    {
      title: '40% dcto en Spotify Premium',
      description: 'Plan Spotify Premium con 40% de descuento para clientes Entel.',
      discount: '40%',
      type: 'PERCENTAGE',
      category: 'Streaming',
      providerId: createdProviders['entel'].id,
      terms: 'Descuento en boleta Entel.',
      validDays: [],
    },
    {
      title: 'Disney+ incluido',
      description: 'Disney+ sin costo adicional en planes seleccionados Entel.',
      discount: 'Incluido',
      type: 'FREEBIE',
      category: 'Streaming',
      providerId: createdProviders['entel'].id,
      terms: 'Planes Entel desde $14.990/mes.',
      validDays: [],
    },
    {
      title: '30% dcto en accesorios Entel',
      description: 'Descuento en accesorios en tiendas Entel.',
      discount: '30%',
      type: 'PERCENTAGE',
      category: 'Tecnología',
      providerId: createdProviders['entel'].id,
      terms: 'Aplica en fundas, cargadores y audífonos.',
      validDays: [],
    },
    {
      title: '20% dcto en Starbucks',
      description: 'Descuento exclusivo en Starbucks para clientes Entel.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['entel'].id,
      terms: 'Presenta tu app Entel al pagar.',
      validDays: [],
    },
    {
      title: '15% dcto en entradas Ticketmaster',
      description: 'Descuento en entradas para conciertos y shows en Ticketmaster.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Eventos',
      providerId: createdProviders['entel'].id,
      terms: 'Sujeto a disponibilidad de eventos.',
      validDays: [],
    },
    {
      title: '20% dcto en Marathon Sport',
      description: 'Descuento en ropa y equipamiento deportivo en Marathon.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Deporte',
      providerId: createdProviders['entel'].id,
      terms: 'Válido en tiendas físicas Marathon Sport.',
      validDays: [],
    },
    {
      title: 'Paramount+ incluido',
      description: 'Acceso a Paramount+ sin costo adicional con planes Entel.',
      discount: 'Incluido',
      type: 'FREEBIE',
      category: 'Streaming',
      providerId: createdProviders['entel'].id,
      terms: 'Planes Entel desde $19.990/mes.',
      validDays: [],
    },

    // ─── Movistar (7 benefits) ───────────────────────────────────────
    {
      title: 'Apple TV+ incluido',
      description: 'Accede a Apple TV+ gratis con tu plan Movistar.',
      discount: 'Incluido',
      type: 'FREEBIE',
      category: 'Streaming',
      providerId: createdProviders['movistar'].id,
      terms: 'Planes Movistar desde $12.990/mes.',
      validDays: [],
    },
    {
      title: '25% dcto en Samsung Store',
      description: 'Descuento en Samsung Store para clientes Movistar.',
      discount: '25%',
      type: 'PERCENTAGE',
      category: 'Tecnología',
      providerId: createdProviders['movistar'].id,
      terms: 'Válido en accesorios y wearables Samsung.',
      validDays: [],
    },
    {
      title: 'Roaming gratis en Latinoamérica',
      description: 'Usa tu plan de datos en todos los países de Latinoamérica.',
      discount: 'Sin costo',
      type: 'FREEBIE',
      category: 'Viajes',
      providerId: createdProviders['movistar'].id,
      terms: 'Planes Full desde $18.990/mes.',
      validDays: [],
    },
    {
      title: '20% dcto en Café Villa Crespo',
      description: 'Descuento en Café Villa Crespo para clientes Movistar.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['movistar'].id,
      terms: 'Válido en consumo en local.',
      validDays: [],
    },
    {
      title: '15% dcto en Zara',
      description: 'Descuento en tiendas Zara para clientes Movistar.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['movistar'].id,
      terms: 'Solo tiendas físicas Zara Chile.',
      validDays: [],
    },
    {
      title: '20% dcto en Cine Hoyts',
      description: 'Descuento en entradas de Cine Hoyts para clientes Movistar.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Cine',
      providerId: createdProviders['movistar'].id,
      terms: 'Válido de lunes a domingo. Excluye 3D premium.',
      validDays: [],
    },
    {
      title: '15% dcto en Gimnasio SportLife',
      description: 'Descuento en membresía SportLife para clientes Movistar.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Deporte',
      providerId: createdProviders['movistar'].id,
      terms: 'Aplica en planes mensuales.',
      validDays: [],
    },

    // ─── Claro (6 benefits) ──────────────────────────────────────────
    {
      title: 'Max (HBO) incluido',
      description: 'Acceso a Max (HBO Max) incluido en tu plan Claro.',
      discount: 'Incluido',
      type: 'FREEBIE',
      category: 'Streaming',
      providerId: createdProviders['claro'].id,
      terms: 'Planes Claro desde $15.990/mes.',
      validDays: [],
    },
    {
      title: '20% dcto en restaurantes Claro',
      description: 'Beneficios gastronómicos en restaurantes partner de Claro.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Restaurante',
      providerId: createdProviders['claro'].id,
      terms: 'Mostrar QR en app Claro.',
      validDays: [],
    },
    {
      title: '15% dcto en Ripley Sport',
      description: 'Descuento en sección deportes de Ripley.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Deporte',
      providerId: createdProviders['claro'].id,
      terms: 'Ropa, calzado y equipamiento deportivo.',
      validDays: [],
    },
    {
      title: '20% dcto en El Café del Cerro',
      description: 'Descuento en El Café del Cerro para clientes Claro.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['claro'].id,
      terms: 'Válido en Santiago y regiones.',
      validDays: [],
    },
    {
      title: "15% dcto en Johnson's (farmacia)",
      description: "Descuento en productos de salud y cuidado personal en Johnson's.",
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Salud',
      providerId: createdProviders['claro'].id,
      terms: 'No aplica medicamentos con receta.',
      validDays: [],
    },
    {
      title: '20% dcto en entradas Feria del Libro',
      description: 'Descuento en entradas para la Feria del Libro y eventos culturales.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Eventos',
      providerId: createdProviders['claro'].id,
      terms: 'Sujeto a disponibilidad de eventos.',
      validDays: [],
    },

    // ─── WOM (5 benefits) ────────────────────────────────────────────
    {
      title: 'Datos ilimitados incluidos',
      description: 'Navega sin límite con datos ilimitados en todos los planes WOM.',
      discount: 'Ilimitado',
      type: 'FREEBIE',
      category: 'Tecnología',
      providerId: createdProviders['wom'].id,
      terms: 'Velocidad reducida después de 30GB.',
      validDays: [],
    },
    {
      title: '50% dcto primer mes',
      description: 'Paga solo el 50% de tu primer mes al cambiarte a WOM.',
      discount: '50%',
      type: 'PERCENTAGE',
      category: 'Tecnología',
      providerId: createdProviders['wom'].id,
      terms: 'Solo nuevos clientes. Portabilidad requerida.',
      validDays: [],
    },
    {
      title: '20% dcto en Cinemark',
      description: 'Descuento en entradas de Cinemark para clientes WOM.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Cine',
      providerId: createdProviders['wom'].id,
      terms: 'Válido en funciones 2D.',
      validDays: [],
    },
    {
      title: '15% dcto en Café Nero',
      description: 'Descuento en Caffè Nero para clientes WOM.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['wom'].id,
      terms: 'Válido en bebidas calientes y frías.',
      validDays: [],
    },
    {
      title: '20% dcto en tiendas Corona',
      description: 'Descuento en tiendas Corona (ropa y hogar) para clientes WOM.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['wom'].id,
      terms: 'Válido en tiendas físicas.',
      validDays: [],
    },

    // ─── CMR Falabella (6 benefits) ──────────────────────────────────
    {
      title: '15% dcto todos los martes',
      description: 'Cada martes 15% de descuento en toda la tienda Falabella.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['cmr-falabella'].id,
      terms: 'Solo los días martes en tiendas físicas y online.',
      validDays: [2],
    },
    {
      title: 'Puntos CMR dobles en combustible',
      description: 'Doble acumulación de puntos al cargar combustible.',
      discount: '2x puntos',
      type: 'SPECIAL',
      category: 'Combustible',
      providerId: createdProviders['cmr-falabella'].id,
      terms: 'Estaciones de servicio afiliadas.',
      validDays: [],
    },
    {
      title: '10% dcto en Café Falabella',
      description: 'Descuento en los cafés dentro de tiendas Falabella.',
      discount: '10%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['cmr-falabella'].id,
      terms: 'Válido en comidas y bebidas.',
      validDays: [],
    },
    {
      title: '20% dcto en Linio electrónica',
      description: 'Descuento en electrónica y tecnología en Linio.cl.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Tecnología',
      providerId: createdProviders['cmr-falabella'].id,
      terms: 'Productos seleccionados.',
      validDays: [],
    },
    {
      title: '20% dcto en Viajes Falabella',
      description: 'Descuento en paquetes de viaje en Viajes Falabella.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Viajes',
      providerId: createdProviders['cmr-falabella'].id,
      terms: 'Paquetes completos vuelo + hotel.',
      validDays: [],
    },
    {
      title: '15% dcto en supermercado Tottus',
      description: 'Descuento martes y jueves en supermercados Tottus.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Supermercado',
      providerId: createdProviders['cmr-falabella'].id,
      terms: 'Compra mínima $15.000.',
      validDays: [2, 4],
    },

    // ─── Ripley Card (6 benefits) ────────────────────────────────────
    {
      title: '20% dcto en Ripley',
      description: 'Descuento permanente en ropa y accesorios en tiendas Ripley.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['ripley-card'].id,
      terms: 'No aplica electrónica. No acumulable con otras promo.',
      validDays: [],
    },
    {
      title: 'Seguro de viaje gratis',
      description: 'Seguro de viaje automático en compras de pasajes con Ripley Card.',
      discount: 'Gratis',
      type: 'FREEBIE',
      category: 'Seguros',
      providerId: createdProviders['ripley-card'].id,
      terms: 'Cobertura hasta USD 50.000.',
      validDays: [],
    },
    {
      title: '20% dcto en Cinemark (Ripley)',
      description: 'Descuento en entradas de Cinemark con Ripley Card.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Cine',
      providerId: createdProviders['ripley-card'].id,
      terms: 'Válido lunes, martes y miércoles.',
      validDays: [1, 2, 3],
    },
    {
      title: '15% dcto en Café Du Monde',
      description: 'Descuento en Café Du Monde para clientes Ripley Card.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['ripley-card'].id,
      terms: 'Válido en tiendas dentro de malls.',
      validDays: [],
    },
    {
      title: '20% dcto en Adidas (Ripley)',
      description: 'Descuento en sección Adidas dentro de Ripley.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Deporte',
      providerId: createdProviders['ripley-card'].id,
      terms: 'Ropa y calzado deportivo Adidas.',
      validDays: [],
    },
    {
      title: '10% dcto en Samsung en Ripley',
      description: 'Descuento en equipos y accesorios Samsung en Ripley.',
      discount: '10%',
      type: 'PERCENTAGE',
      category: 'Tecnología',
      providerId: createdProviders['ripley-card'].id,
      terms: 'Aplica en compras mayores a $50.000.',
      validDays: [],
    },

    // ─── La Polar Card (5 benefits) ──────────────────────────────────
    {
      title: '30% dcto en ropa La Polar',
      description: 'Descuento en toda la línea de ropa de La Polar.',
      discount: '30%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['la-polar-card'].id,
      terms: 'Temporadas regulares. No aplica en liquidación.',
      validDays: [],
    },
    {
      title: '24 cuotas sin interés',
      description: 'Compra en La Polar en hasta 24 cuotas sin interés.',
      discount: '24 cuotas sin interés',
      type: 'SPECIAL',
      category: 'Tecnología',
      providerId: createdProviders['la-polar-card'].id,
      terms: 'Compras superiores a $30.000.',
      validDays: [],
    },
    {
      title: '20% dcto en calzado',
      description: 'Descuento en toda la sección de calzado de La Polar.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Moda',
      providerId: createdProviders['la-polar-card'].id,
      terms: 'Excluye marcas deportivas importadas.',
      validDays: [],
    },
    {
      title: '15% dcto en Cine La Polar',
      description: 'Descuento en cines ubicados en malls La Polar.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Cine',
      providerId: createdProviders['la-polar-card'].id,
      terms: 'Válido en funciones seleccionadas.',
      validDays: [],
    },
    {
      title: '10% dcto en cafetería La Polar',
      description: 'Descuento en cafeterías dentro de tiendas La Polar.',
      discount: '10%',
      type: 'PERCENTAGE',
      category: 'Café',
      providerId: createdProviders['la-polar-card'].id,
      terms: 'Válido en alimentos y bebidas.',
      validDays: [],
    },

    // ─── MetLife (5 benefits) ─────────────────────────────────────────
    {
      title: '40% dcto en dentista',
      description: 'Descuento en atención dental en clínicas afiliadas MetLife.',
      discount: '40%',
      type: 'PERCENTAGE',
      category: 'Salud',
      providerId: createdProviders['metlife'].id,
      terms: 'Red de 300+ dentistas. Presenta tu póliza.',
      validDays: [],
    },
    {
      title: 'Telemedicina gratuita',
      description: 'Consultas médicas online ilimitadas incluidas en tu seguro.',
      discount: 'Gratis',
      type: 'FREEBIE',
      category: 'Salud',
      providerId: createdProviders['metlife'].id,
      terms: 'Disponible 24/7. Titular y cargas familiares.',
      validDays: [],
    },
    {
      title: '20% dcto en ópticas',
      description: 'Descuento en ópticas y lentes con cobertura MetLife.',
      discount: '20%',
      type: 'PERCENTAGE',
      category: 'Salud',
      providerId: createdProviders['metlife'].id,
      terms: 'Ópticas Alain Afflelou y participantes.',
      validDays: [],
    },
    {
      title: '15% dcto en farmacias Ahumada',
      description: 'Descuento en Farmacias Ahumada con seguro MetLife activo.',
      discount: '15%',
      type: 'PERCENTAGE',
      category: 'Salud',
      providerId: createdProviders['metlife'].id,
      terms: 'Productos de venta libre y cuidado personal.',
      validDays: [],
    },
    {
      title: 'Descuento en laboratorios clínicos',
      description: 'Descuento en exámenes de laboratorio en clínicas afiliadas.',
      discount: '30%',
      type: 'PERCENTAGE',
      category: 'Salud',
      providerId: createdProviders['metlife'].id,
      terms: 'Red de laboratorios partner MetLife.',
      validDays: [],
    },
  ];

  for (const benefit of benefits) {
    await prisma.benefit.create({ data: benefit });
  }

  // Create demo user
  const hashedPassword = await bcrypt.hash('demo1234', 10);
  await prisma.user.upsert({
    where: { email: 'demo@perksly.app' },
    update: {},
    create: {
      email: 'demo@perksly.app',
      password: hashedPassword,
      name: 'Usuario Demo',
    },
  });

  console.log('Seeding completed successfully!');
  console.log(`Created ${providers.length} providers`);
  console.log(`Created ${benefits.length} benefits`);
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
